services:
  db:
    image: postgres:16-alpine
    container_name: animepass_db
    environment:
      POSTGRES_USER: animepass
      POSTGRES_PASSWORD: animepass_secret
      POSTGRES_DB: animepass_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U animepass -d animepass_db"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
